name: ereports-platform CI/CD

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.4.0
        uses: actions/setup-node@v1
        with:
          node-version: "15.4.0"

      - run: npm ci
      - name: Run tests
        run: npm test
        env:
          CI: true
      - run: npm run build

  # deploy-docker:
  #   runs-on: ubuntu-latest
  #   run: build image
  #   run: publish image

  # deploy-server:
  #   run: connect with ssh
  #   run: pull docker image
  #   run: rerun image
